name: Build published docker image

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    #--- Set permissions to ephemeral GITHUB_TOKEN for job actions
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout and download repository to workflow runner
        uses: actions/checkout@v4

      - name: Set up docker builder
        uses: docker/setup-buildx-action@v3

      - name: Login to github container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get metadata from docker image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push image to github container registry
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          push: true
          tags: ${{ steps.meta.outputs.tags }}